arb-dir: lib/l10n
output-class: CoreLocalizations
output-localization-file: core_localizations.dart
output-dir: lib/l10n/generated
template-arb-file: l10n_en.arb
preferred-supported-locales: ["en"]
synthetic-package: false
# nullable-getter: false
untranslated-messages-file: lib/l10n/untranslated.json