name: core
description:
  A package that provides basic utilities such as Themes and HTTP Errors Page.
  Great for creating multiple flutter apps as a portfolio.
version: 1.2.1
# homepage:
publish_to: "none"

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  generate: true
